# Generated by Django 5.1.7 on 2025-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('current_address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('social_media_accounts', models.TextField(blank=True, help_text='List of social media links/accounts', null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('course_studied', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('seeking', 'Seeking Employment')], max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_acquired', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('monthly_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('testimonial', models.TextField(blank=True, help_text='Quote or story about their experience with the training program', null=True)),
                ('mentorship_interest', models.BooleanField(default=False, help_text='Interest in mentoring current students')),
                ('networking_interest', models.BooleanField(default=False, help_text='Interest in attending alumni events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
