# Generated by Django 5.2.4 on 2025-07-28 19:43

import alumni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumniprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a passport-style photograph', null=True, upload_to=alumni.models.user_profile_image_path),
        ),
    ]
