"""
Django settings for alumni_management_system project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


ALLOWED_HOSTS = [
    'alumni-management-system-h0qp.onrender.com',
    'alumni.henrydjabamemorialfdn.org.gh',
    'localhost',
    '127.0.0.1'
]

# SECURITY WARNING: don't run with debug turned on in production!
# Check for specific environment or hostname to determine if we're in development
IS_DEVELOPMENT = os.environ.get('DJANGO_ENV') == 'development' or 'render.com' not in ALLOWED_HOSTS[0]
DEBUG = IS_DEVELOPMENT if os.environ.get('DEBUG') is None else os.environ.get('DEBUG', 'False').lower() == 'true'

print(f"Running with DEBUG={DEBUG} (IS_DEVELOPMENT={IS_DEVELOPMENT})")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'alumni',
    # 'sslserver'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alumni_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alumni_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# SQLite Configuration (temporarily for testing role system)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL Configuration (switch back when conda env is active)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv('DB_NAME'),
#         "USER": os.getenv('USER'),
#         "PASSWORD": os.getenv('DB_PASSWORD'),
#         "HOST": os.getenv('DB_HOST'),
#         "PORT": "5432",
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "alumni",
        "USER": "postgres",
        "PASSWORD": "Postgres.ayadata.21",
        "HOST": "3.232.163.161",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files configuration for production
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    
    # CSRF settings
    CSRF_TRUSTED_ORIGINS = [
        'https://alumni-management-system-h0qp.onrender.com',
        'https://alumni.henrydjabamemorialfdn.org.gh'
    ]
    
    # Content security
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_BROWSER_XSS_FILTER = True
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_PRELOAD = False
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'  # Redirect to home page after login
LOGOUT_URL = '/logout'
# LOGOUT_REDIRECT_URL = '/login/'

# Email settings for password reset
# Try to use SendGrid, but fall back to console backend if not available
try:
    import sendgrid_backend
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    print("Using SendGrid email backend")
except ImportError:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("SendGrid not available, using console email backend")

# Add sendgrid_backend to installed apps if available
try:
    import sendgrid_backend
    INSTALLED_APPS.append('sendgrid_backend')
    print("Added sendgrid_backend to INSTALLED_APPS")
except ImportError:
    print("sendgrid_backend not installed, skipping app registration")

# SendGrid API key - prefer environment variable but fall back to direct setting if needed
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')

# Set to True to ensure subjects are explicitly set in code rather than from templates
# This helps ensure emails have proper subjects and don't go to spam
SENDGRID_TEMPLATE_SUBJECT_OVERRIDE = True

# Set to False in production to actually send emails
SENDGRID_SANDBOX_MODE_IN_DEBUG = False

# Email tracking features (optional)
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS_HTML = True
SENDGRID_ECHO_TO_STDOUT = True # Prints email content to console in DEBUG mode

# Keep your existing email address configuration
DEFAULT_FROM_EMAIL = 'Henry Djaba Memorial Foundation <info@henrydjabamemorialfdn.org.gh>'
EMAIL_SUBJECT_PREFIX = '[HDMF Alumni Portal] '

# For development - emails will be printed to console
# For production, configure these with your email provider:
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# DEFAULT_FROM_EMAIL = 'Henry Djaba Memorial Foundation <noreply@henrydjaba.org>'
# EMAIL_SUBJECT_PREFIX = '[HDMF Alumni Portal] '
